In [27]:
import pandas as pd

In [28]:
dataset = pd.read_csv("dataset.csv")
dataset.head()

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,speechiness,tempo,artists_song
0,0.285,2000,0.00239,Coldplay,0.429,266773,0.661,0,3AJwUDP919kvQ9QcozQPxg,0.000121,11,0.2340,-7.227,1,Yellow,84,0.0281,173.372,Coldplay - Yellow
1,0.613,2000,0.14300,OutKast,0.843,270507,0.806,1,0I3q5fE6wg7LIfHGngUTnV,0.000000,4,0.0771,-5.946,0,Ms. Jackson,80,0.2690,94.948,OutKast - Ms. Jackson
2,0.400,2000,0.00958,Linkin Park,0.556,216880,0.864,0,60a0Rd6pjrkxjPbaKzXjfq,0.000000,3,0.2090,-5.870,0,In the End,84,0.0584,105.143,Linkin Park - In the End
3,0.543,2000,0.00664,3 Doors Down,0.545,233933,0.865,0,6ZOBP3NvffbU4SZcrnt1k6,0.000011,11,0.1680,-5.708,0,Kryptonite,78,0.0286,99.009,3 Doors Down - Kryptonite
4,0.760,2000,0.03020,Eminem,0.949,284200,0.661,1,3yfqSUWxFvZELEM4PmlwIR,0.000000,5,0.0454,-4.244,0,The Real Slim Shady,80,0.0572,104.504,Eminem - The Real Slim Shady

##### Preparando o conjunto de dados para o Clustering

In [29]:
# Explicit - Se a música possui letras explícitas
# Key - Qual a chave geral da faixa (teoria musical)
# Mode - Modalidade de uma faixa (teoria musical)

# Retiradas por apresentarem pouca relação direta entre as músicas


dataset.drop(['explicit', 'key', 'mode'], axis = 1)

,valence,year,acousticness,artists,danceability,duration_ms,energy,id,instrumentalness,liveness,loudness,name,popularity,speechiness,tempo,artists_song
0,0.285,2000,0.00239,Coldplay,0.429,266773,0.661,3AJwUDP919kvQ9QcozQPxg,0.000121,0.2340,-7.227,Yellow,84,0.0281,173.372,Coldplay - Yellow
1,0.613,2000,0.14300,OutKast,0.843,270507,0.806,0I3q5fE6wg7LIfHGngUTnV,0.000000,0.0771,-5.946,Ms. Jackson,80,0.2690,94.948,OutKast - Ms. Jackson
2,0.400,2000,0.00958,Linkin Park,0.556,216880,0.864,60a0Rd6pjrkxjPbaKzXjfq,0.000000,0.2090,-5.870,In the End,84,0.0584,105.143,Linkin Park - In the End
3,0.543,2000,0.00664,3 Doors Down,0.545,233933,0.865,6ZOBP3NvffbU4SZcrnt1k6,0.000011,0.1680,-5.708,Kryptonite,78,0.0286,99.009,3 Doors Down - Kryptonite
4,0.760,2000,0.03020,Eminem,0.949,284200,0.661,3yfqSUWxFvZELEM4PmlwIR,0.000000,0.0454,-4.244,The Real Slim Shady,80,0.0572,104.504,Eminem - The Real Slim Shady
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20306,0.187,2020,0.57400,Bazzi,0.445,176250,0.330,0PUkanqCGTb6qseXPKOw1F,0.000000,0.1020,-8.121,I Don't Think I'm Okay,69,0.0429,128.025,Bazzi - I Don't Think I'm Okay
20307,0.240,2020,0.81500,Bryson Tiller,0.467,179188,0.429,6Iw6fQVKZi0fWtEQBrTFcP,0.000052,0.1770,-8.689,Timeless Interlude,65,0.0964,148.530,Bryson Tiller - Timeless Interlude
20308,0.466,2020,0.31000,Fleet Foxes,0.562,253613,0.686,308prODCCD0O660tIktbUi,0.022500,0.1250,-8.480,Sunblind,66,0.0249,103.054,Fleet Foxes - Sunblind
20309,0.522,2020,0.20400,Gunna,0.598,230600,0.472,2f8y4CuG57UJEmkG3ujd0D,0.000015,0.1080,-10.991,NASTY GIRL / ON CAMERA,66,0.2580,120.080,Gunna - NASTY GIRL / ON CAMERA
20310,0.195,2020,0.00998,Eminem,0.671,337147,0.623,5SiZJoLXp3WOl3J4C8IK0d,0.000008,0.6430,-7.161,Darkness,70,0.3080,75.055,Eminem - Darkness

In [30]:
# Criar uma cópia do dataset (alterado), para que possamos salvar o original

from sklearn.preprocessing import OneHotEncoder

# Usando OneHot para não perder informação sobre os artistas
OneHot = OneHotEncoder(dtype=int)
novas_colunas = OneHot.fit_transform(dataset[['artists']]).toarray()

# Criando um dataset com o OneHot
dataset_alterado = dataset.drop('artists', axis = 1)
dataset_alterado = pd.concat([dataset_alterado, pd.DataFrame(novas_colunas, columns=OneHot.get_feature_names_out(['artists']))], axis=1)

In [31]:
dataset_alterado.head()

,valence,year,acousticness,danceability,duration_ms,energy,explicit,id,instrumentalness,key,...,artists_Zara Larsson,artists_Zedd,artists_alt-J,artists_blackbear,artists_blink-182,artists_deadmau5,artists_for KING & COUNTRY,artists_fun.,artists_girl in red,artists_iann dior
0,0.285,2000,0.00239,0.429,266773,0.661,0,3AJwUDP919kvQ9QcozQPxg,0.000121,11,...,0,0,0,0,0,0,0,0,0,0
1,0.613,2000,0.14300,0.843,270507,0.806,1,0I3q5fE6wg7LIfHGngUTnV,0.000000,4,...,0,0,0,0,0,0,0,0,0,0
2,0.400,2000,0.00958,0.556,216880,0.864,0,60a0Rd6pjrkxjPbaKzXjfq,0.000000,3,...,0,0,0,0,0,0,0,0,0,0
3,0.543,2000,0.00664,0.545,233933,0.865,0,6ZOBP3NvffbU4SZcrnt1k6,0.000011,11,...,0,0,0,0,0,0,0,0,0,0
4,0.760,2000,0.03020,0.949,284200,0.661,1,3yfqSUWxFvZELEM4PmlwIR,0.000000,5,...,0,0,0,0,0,0,0,0,0,0

In [32]:
# Retirando Colunas Não-Numéricas
dataset_alterado = dataset_alterado.drop(['id', 'name', 'artists_song'], axis=1)

In [33]:
dataset_alterado.shape

(20311, 890)

#### Últimos Ajustes (PCA e Padronização)

In [34]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import numpy as np

SEED = 10
np.random.seed(SEED)

pipeline = Pipeline([('scaler', StandardScaler()),
                     ('PCA', PCA(n_components = 0.7, random_state=SEED))])
dataset_alterado = pipeline.fit_transform(dataset_alterado)
dataset_alterado = pd.DataFrame(data=dataset_alterado)

In [35]:
dataset_alterado.head()

,0,1,2,3,4,5,6,7,8,9,...,603,604,605,606,607,608,609,610,611,612
0,0.378041,-1.105670,-0.217875,2.141618,0.460543,0.389330,0.357378,-0.829060,-1.064067,-2.822201,...,0.008899,-0.030201,-0.007721,-0.007201,0.009958,-0.013029,-0.003145,0.015032,-0.038177,-1.981588e-12
1,-1.835784,0.968268,1.957886,-2.040361,0.482239,1.226603,-0.639418,-1.116720,0.601654,-1.535073,...,-0.035774,-0.053345,0.024401,0.007943,0.021621,-0.035924,-0.023443,0.001881,-0.031168,-2.791477e-13
2,-0.812090,-0.923825,0.059168,0.972975,-0.437157,1.290976,1.071816,0.449164,1.948167,-1.273368,...,0.013371,0.009657,-0.019426,-0.004488,-0.002567,-0.002016,-0.014941,0.002420,-0.012432,-1.268027e-12
3,-0.784928,-1.590062,-0.058206,0.553700,-0.130400,1.856148,1.122687,-1.812624,0.509192,-1.145719,...,0.052985,-0.098214,-0.002778,-0.071470,0.019352,0.040598,-0.160847,0.016884,-0.056636,-1.713191e-12
4,-2.168298,1.079448,1.225286,-1.395836,1.274807,1.751917,-0.630658,-0.029179,0.417433,-2.159679,...,-0.010668,-0.004384,0.003494,-0.005433,0.006327,-0.009567,0.007437,0.013157,-0.014763,3.213974e-13

#### Clusterizando as Músicas

In [36]:
from sklearn.cluster import KMeans

model = KMeans(n_clusters=50, verbose=False, random_state=SEED)
model.fit(dataset_alterado)

dataset_alterado['grupo_cluster'] = model.predict(dataset_alterado)
dataset_alterado['artistas'] = dataset['artists']
dataset_alterado['musica'] = dataset['name']

In [37]:
dataset_alterado.head()

,0,1,2,3,4,5,6,7,8,9,...,606,607,608,609,610,611,612,grupo_cluster,artistas,musica
0,0.378041,-1.105670,-0.217875,2.141618,0.460543,0.389330,0.357378,-0.829060,-1.064067,-2.822201,...,-0.007201,0.009958,-0.013029,-0.003145,0.015032,-0.038177,-1.981588e-12,41,Coldplay,Yellow
1,-1.835784,0.968268,1.957886,-2.040361,0.482239,1.226603,-0.639418,-1.116720,0.601654,-1.535073,...,0.007943,0.021621,-0.035924,-0.023443,0.001881,-0.031168,-2.791477e-13,1,OutKast,Ms. Jackson
2,-0.812090,-0.923825,0.059168,0.972975,-0.437157,1.290976,1.071816,0.449164,1.948167,-1.273368,...,-0.004488,-0.002567,-0.002016,-0.014941,0.002420,-0.012432,-1.268027e-12,42,Linkin Park,In the End
3,-0.784928,-1.590062,-0.058206,0.553700,-0.130400,1.856148,1.122687,-1.812624,0.509192,-1.145719,...,-0.071470,0.019352,0.040598,-0.160847,0.016884,-0.056636,-1.713191e-12,41,3 Doors Down,Kryptonite
4,-2.168298,1.079448,1.225286,-1.395836,1.274807,1.751917,-0.630658,-0.029179,0.417433,-2.159679,...,-0.005433,0.006327,-0.009567,0.007437,0.013157,-0.014763,3.213974e-13,7,Eminem,The Real Slim Shady

In [38]:
# As colunas 0 e 1 serão usadas como coordenadas espaciais para o recomendador.
dataset_final = dataset_alterado[[0, 1,'grupo_cluster', 'artistas', 'musica']]
dataset_final['id'] = dataset['id']

/tmp/ipykernel_94801/3035865212.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset_final['id'] = dataset['id']

In [39]:
dataset_final

,0,1,grupo_cluster,artistas,musica,id
0,0.378041,-1.105670,41,Coldplay,Yellow,3AJwUDP919kvQ9QcozQPxg
1,-1.835784,0.968268,1,OutKast,Ms. Jackson,0I3q5fE6wg7LIfHGngUTnV
2,-0.812090,-0.923825,42,Linkin Park,In the End,60a0Rd6pjrkxjPbaKzXjfq
3,-0.784928,-1.590062,41,3 Doors Down,Kryptonite,6ZOBP3NvffbU4SZcrnt1k6
4,-2.168298,1.079448,7,Eminem,The Real Slim Shady,3yfqSUWxFvZELEM4PmlwIR
...,...,...,...,...,...,...
20306,1.289224,2.028642,36,Bazzi,I Don't Think I'm Okay,0PUkanqCGTb6qseXPKOw1F
20307,1.042660,2.314540,36,Bryson Tiller,Timeless Interlude,6Iw6fQVKZi0fWtEQBrTFcP
20308,0.885203,0.564691,41,Fleet Foxes,Sunblind,308prODCCD0O660tIktbUi
20309,-0.525831,3.565280,36,Gunna,NASTY GIRL / ON CAMERA,2f8y4CuG57UJEmkG3ujd0D
20310,-1.495765,2.396163,7,Eminem,Darkness,5SiZJoLXp3WOl3J4C8IK0d

In [40]:
dataset_final.to_csv("musicas_agrupadas.csv")